APP_NAME := airfoil

# VARIANT_FILTER := airfoil_seq airfoil_genseq airfoil_vec airfoil_openmp
VARIANT_FILTER := airfoil_mpi_openmp

include ../../../../../makefiles/common.mk
include ../../../../../makefiles/c_app.mk
