APP_NAME := airfoil

# VARIANT_FILTER := airfoil_seq airfoil_genseq airfoil_vec airfoil_openmp airfoil_mpi_seq airfoil_mpi_genseq airfoil_mpi_vec airfoil_mpi_openmp
VARIANT_FILTER := airfoil_mpi_seq
# VARIANT_FILTER := airfoil_seq

include ../../../../../makefiles/common.mk
include ../../../../../makefiles/c_app.mk
